### PR TITLE
Adds websearch support

### PR DESCRIPTION
**Pull request by gdestuynder**
Mostly experimental, to see if it adds value
That would fix https://github.com/caggle/vautomator-standalone/issues/27

### CODE REVIEW

**Comment by caggle** [comment]
Actually we should write tests for the new class, but since currently our class structure is a bit messed up, I will merge this and address the re-writing of classes & unit tests in another PR.

**Comment by claudijd** [comment]
FWIW, I think we should focus more on getting new functionality into vautomator-serverless and try to keep this project as maintenance as possible, just so we're not splitting our time between the two.

**Comment by gdestuynder** [comment]
the thing is, i use this right now. should i use the vautormator-serverless? as soon as i switch ill stop PR'ing here :)

also: definitly agree for tests, there were no prior tests of this type so didnt add any, but did notice there were missing hehe

**Comment by caggle** [comment]
`vautomator-serverless` is not ready for production use yet.

I don't have a problem with working on this at the same time of working on vautomator-serverless, however we are not formally tracking the work on this one on Jira, therefore it is de-prioritised in my mind. Maybe we should add it under https://jira.mozilla.com/browse/EIS-39 as a task or something along those lines so it is tracked.

Also, we can certainly re-apply some of the code from either project to another (unit-testable classes for example), so I don't see it necessarily a waste of effort.

**Pull request merged**
